Integrate LighthouseCI (#86)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,9 +2,9 @@ name: CI
 
 on:
   push:
-    branches: ['master']
+    branches: ["master"]
   pull_request:
-    branches: ['master']
+    branches: ["master"]
 
 jobs:
   build:
@@ -14,15 +14,77 @@ jobs:
       matrix:
         node-version: [20.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
-    
+
     steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-          cache: 'npm'
-      - run: npm ci
-      - run: npm test
+          cache: "npm"
 
-      
+      - name: Install & Build
+        run: |
+          npm ci
+          npm run build
+
+      - name: Waiting for 200 from the Netlify Preview
+        uses: jakepartusch/wait-for-netlify-action@v1
+        id: waitFor200
+        with:
+          site_name: "danifdz"
+          max_timeout: 120
+
+      - name: Lighthouse CI mobile audit
+        id: lighthouse_audit_mobile
+        run: |
+          npm install -g @lhci/cli@0.13.x
+          lhci autorun --collect.url=${{ steps.waitFor200.outputs.url }} --collect.settings.budgetPath="budget.json" --assert.budgetsFile="budget.json" --upload.reportFilenamePattern="lighthouse-results-mobile.%%EXTENSION%%" || echo "LHCI failed!"
+
+      - name: Format lighthouse score mobile
+        id: format_lighthouse_score_mobile
+        uses: actions/github-script@v5
+        with:
+          script: |
+            const lighthouseReportFormatter = require('./.github/workflows/lh-report-formatter.js');
+            const comment = lighthouseReportFormatter.createComment("./lhci/lighthouse-results-mobile.json", "mobile");
+            core.setOutput("comment", comment);
+
+      - name: Add Lighthouse mobile stats as comment
+        id: comment_to_pr_mobile
+        uses: marocchino/sticky-pull-request-comment@v2.9.0
+        with:
+          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          number: ${{ github.event.pull_request.number }}
+          header: lighthouse-mobile
+          message: ${{ steps.format_lighthouse_score_mobile.outputs.comment }}
+
+      - name: Lighthouse CI desktop audit
+        id: lighthouse_audit_desktop
+        run: |
+          npm install -g @lhci/cli@0.13.x
+          lhci autorun --collect.url=${{ steps.waitFor200.outputs.url }} --collect.settings.budgetPath="budget-desktop.json" --assert.budgetsFile="budget-desktop.json" --collect.settings.preset=desktop --upload.reportFilenamePattern="lighthouse-results-desktop.%%EXTENSION%%" || echo "LHCI failed!"
+
+      - name: Format lighthouse score desktop
+        id: format_lighthouse_score_desktop
+        uses: actions/github-script@v5
+        with:
+          script: |
+            const lighthouseReportFormatter = require('./.github/workflows/lh-report-formatter.js');
+            const comment = lighthouseReportFormatter.createComment("./lhci/lighthouse-results-desktop.json", "desktop");
+            core.setOutput("comment", comment);
+
+      - name: Add Lighthouse desktop stats as comment
+        id: comment_to_pr_desktop
+        uses: marocchino/sticky-pull-request-comment@v2.9.0
+        with:
+          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          number: ${{ github.event.pull_request.number }}
+          header: lighthouse-desktop
+          message: ${{ steps.format_lighthouse_score_desktop.outputs.comment }}
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: Lighthouse reports
+          path: ./lhci
